name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            set -e

            APP_DIR=/opt/react-bah

            # Criar pasta se não existir e garantir permissões
            sudo mkdir -p \$APP_DIR
            sudo chown -R ${{ secrets.SSH_USER }}:$${{ secrets.SSH_USER }} \$APP_DIR

            # Atualizar código
            cd \$APP_DIR || exit
            if [ ! -d .git ]; then
              git clone https://github.com/koddoki/react-bah.git \$APP_DIR
            fi
            git fetch origin main
            git reset --hard origin/main

            # Instalar dependências e build
            npm ci
            npm run build

            # Rodar/reiniciar com PM2
            pm2 restart next-app || sudo pm2 start npm --name next-app -- run start
            pm2 save
          "
